### ISSUE TITLE
Option like `apertium-deshtml -o` / `apertium -H` for inserting ❡ at end of headers

### ISSUE THREAD

**Issue by unhammer** [TinoDidriksen/Transfuse#26] opened 2023-08-14 09:44 UTC
```
$ echo '<h1>angrepet</h1>' | apertium-deshtml -o
.[][<h1>]angrepet[]❡.[][<\/h1>
]
```

```
$ grep -w H /usr/bin/apertium
    H) FORMAT_OPTIONS+=(-o) ;;
```

but it has no effect when running under transfuse, e.g. I made a silly rule to select participle in headings, which works in non-transfuse pipelines

```
$ echo '<h1>angrepet</h1>' | apertium-deshtml -o | apertium -f none -d . nob-nno_e|apertium-rehtml
<h1>angripe</h1>
$ export APERTIUM_TRANSFUSE=no && echo '<h1>angrepet</h1>' | apertium -H -f html -d . nob-nno_e
<h1>angripe</h1>
```

but not in transfuse pipelines:
```
$ export APERTIUM_TRANSFUSE=yes && echo '<h1>angrepet</h1>' | apertium -H -f html -d . nob-nno_e
<h1>angrepet</h1>
```

**Comment by TinoDidriksen** [comment] 2023-08-14 11:55
Duplicate of https://github.com/TinoDidriksen/Transfuse/issues/15 - and now seems evident it's a recurring pain point.

**Closed as completed by TinoDidriksen** 2023-08-14 11:55 UTC
Labels: duplicate

**Comment by unhammer** [comment] 2023-08-14 12:46
doh, I may have searched for the issue in the apertium repo instead of transfuse
